source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '10.0'
## ignore warning
inhibit_all_warnings!

target 'Meetyou' do
  use_frameworks!


#YYKit 高性能组件
#pod 'YYKit'                            , '1.0.9'
# YYKit 的一套分类
pod 'YYCategories'                      , '1.0.4'
# 富文本
pod 'YYText'                            , '1.0.7'
# 字典转模型
pod 'YYModel'                           , '1.0.4'
# YYImage
pod 'YYImage'                           , '1.0.4'

# 消息链
# pod 'ReactiveCocoa'                     ,'2.5'
# 适配Xcode9.0 iOS 11
pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
# 网络请求
pod 'AFNetworking'                      , '3.1.0'
# 加密
pod 'CocoaSecurity'                     , '1.2.4'

# 字典转模型 该项目使用YYModel
pod 'MJExtension'                       , '3.0.13'
pod 'MJRefresh'                         , '3.1.12'

# 状态栏通知
pod 'JDStatusBarNotification'           , '1.5.5'

# HUD
pod 'MBProgressHUD'                     , '1.1.0'
pod 'SVProgressHUD'                     , '2.1.2'

# 布局相关
pod 'Masonry'

# FaceBook KVO（优雅的代替系统原生的KVO）
pod 'KVOController'                     , '1.2.0'

# pop动画
pod 'pop'                               , '1.0.10'
# 键盘管理
pod 'IQKeyboardManager'                 , '6.5.5'

# 侧滑手势
pod 'FDFullscreenPopGesture'            , '1.1'


# SVG 展示
pod 'SVGKit'

  # Pods for Meetyou

end
